### ISSUE TITLE
[ReplicaController]: Replica setters can only be called inside write functions 

### ISSUE THREAD

**Issue by 3gData** [MadStudioRoblox/ReplicaService#7]
![image](https://user-images.githubusercontent.com/91347920/216978570-1a5a49ed-2c9a-4f9b-a33f-68cbf4f9beaf.png)

This code is located inside of the WriteLib.

![image](https://user-images.githubusercontent.com/91347920/216978691-9999ff77-256a-4011-ac0c-34196270a55d.png)

**Comment by LM-loleris** [comment]
That's intentional ReplicaService behaviour - in ReplicaService state can only be controlled by the server. Data setters client-side can only be used within write functions which can only be invoked by the server.
